### ISSUE TITLE
Wallet address, hovering it, should show the address

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap-demo#38]
<img width="598" alt="Screen Shot 2022-04-13 at 5 14 37 PM" src="https://user-images.githubusercontent.com/3941923/163213181-aba09067-3bac-43c3-a17b-14d8fc237b5c.png">

**Comment by pixelsbyeryc** [comment]
Do you think adding extra functionality to it would be cool?

uniswap has a modal that opens when you click the wallet. It provides extra information about the wallet you’re connected with, and actions to change the wallet, etc.

It also shows your balance.

I mentioned it in https://github.com/FuelLabs/swayswap/pull/53#issuecomment-1112911082 with a design example.
